shamefullyHoist: true

ignoreWorkspaceRootCheck: true

trustPolicy: no-downgrade

blockExoticSubdeps: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - typescript
  - typescript-eslint
  - '@typescript-eslint/*'
